In [29]:
import folium
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
from shapely.geometry import box
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

In [30]:
import matplotlib.font_manager as fm

# 한국어 출력을 위한 폰트 설정
plt.rc('font', family='NanumGothic') 

# 마이너스 기호가 깨지는 것을 방지
plt.rcParams['axes.unicode_minus'] = False

In [31]:
gdf = gpd.read_file("data/읍면동/emd.shp", encoding="euc-kr")

In [32]:
gdf

,EMD_CD,EMD_ENG_NM,EMD_KOR_NM,geometry
0,11110101,Cheongun-dong,청운동,"POLYGON ((953700.022 1954605.065, 953693.871 1..."
1,11110102,Singyo-dong,신교동,"POLYGON ((953233.465 1953996.984, 953235.183 1..."
2,11110103,Gungjeong-dong,궁정동,"POLYGON ((953560.228 1954257.466, 953561.190 1..."
3,11110104,Hyoja-dong,효자동,"POLYGON ((953519.843 1953890.785, 953518.489 1..."
4,11110105,Changseong-dong,창성동,"POLYGON ((953516.123 1953734.362, 953516.526 1..."
...,...,...,...,...
5061,52800390,Sangseo-myeon,상서면,"POLYGON ((924979.638 1740610.214, 924985.428 1..."
5062,52800400,Haseo-myeon,하서면,"POLYGON ((924910.563 1749481.985, 924971.300 1..."
5063,52800410,Julpo-myeon,줄포면,"POLYGON ((929554.188 1736493.399, 929554.106 1..."
5064,52800420,Wido-myeon,위도면,"MULTIPOLYGON (((890358.231 1737258.351, 890358..."
5065,41590140,None,새솔동,"POLYGON ((938339.989 1921241.319, 938340.046 1..."

In [33]:
gdf = gdf.drop(columns=["EMD_ENG_NM"])

In [34]:
gdf.head()

     EMD_CD EMD_KOR_NM                                           geometry
0  11110101        청운동  POLYGON ((953700.022 1954605.065, 953693.871 1...
1  11110102        신교동  POLYGON ((953233.465 1953996.984, 953235.183 1...
2  11110103        궁정동  POLYGON ((953560.228 1954257.466, 953561.190 1...
3  11110104        효자동  POLYGON ((953519.843 1953890.785, 953518.489 1...
4  11110105        창성동  POLYGON ((953516.123 1953734.362, 953516.526 1...

In [35]:
gdf = gdf[gdf['EMD_CD'].astype(str).str.startswith('11')]
gdf

       EMD_CD EMD_KOR_NM                                           geometry
0    11110101        청운동  POLYGON ((953700.022 1954605.065, 953693.871 1...
1    11110102        신교동  POLYGON ((953233.465 1953996.984, 953235.183 1...
2    11110103        궁정동  POLYGON ((953560.228 1954257.466, 953561.190 1...
3    11110104        효자동  POLYGON ((953519.843 1953890.785, 953518.489 1...
4    11110105        창성동  POLYGON ((953516.123 1953734.362, 953516.526 1...
..        ...        ...                                                ...
462  11740106        둔촌동  POLYGON ((969669.593 1948748.489, 969656.716 1...
463  11740107        암사동  POLYGON ((968514.203 1950677.234, 968505.336 1...
464  11740108        성내동  POLYGON ((967686.073 1948534.011, 967685.029 1...
465  11740109        천호동  POLYGON ((968336.280 1950222.697, 968337.437 1...
466  11740110        강일동  POLYGON ((970882.440 1951500.730, 970882.447 1...

[467 rows x 3 columns]

In [36]:
gdf = gdf.rename(columns={'EMD_CD':'읍면동_코드', 'EMD_KOR_NM':'읍면동_이름'})
gdf

       읍면동_코드 읍면동_이름                                           geometry
0    11110101    청운동  POLYGON ((953700.022 1954605.065, 953693.871 1...
1    11110102    신교동  POLYGON ((953233.465 1953996.984, 953235.183 1...
2    11110103    궁정동  POLYGON ((953560.228 1954257.466, 953561.190 1...
3    11110104    효자동  POLYGON ((953519.843 1953890.785, 953518.489 1...
4    11110105    창성동  POLYGON ((953516.123 1953734.362, 953516.526 1...
..        ...    ...                                                ...
462  11740106    둔촌동  POLYGON ((969669.593 1948748.489, 969656.716 1...
463  11740107    암사동  POLYGON ((968514.203 1950677.234, 968505.336 1...
464  11740108    성내동  POLYGON ((967686.073 1948534.011, 967685.029 1...
465  11740109    천호동  POLYGON ((968336.280 1950222.697, 968337.437 1...
466  11740110    강일동  POLYGON ((970882.440 1951500.730, 970882.447 1...

[467 rows x 3 columns]

In [37]:
gdf['시군구_코드'] = gdf['읍면동_코드'].astype(str).str[:5]

In [38]:
gdf

       읍면동_코드 읍면동_이름                                           geometry 시군구_코드
0    11110101    청운동  POLYGON ((953700.022 1954605.065, 953693.871 1...  11110
1    11110102    신교동  POLYGON ((953233.465 1953996.984, 953235.183 1...  11110
2    11110103    궁정동  POLYGON ((953560.228 1954257.466, 953561.190 1...  11110
3    11110104    효자동  POLYGON ((953519.843 1953890.785, 953518.489 1...  11110
4    11110105    창성동  POLYGON ((953516.123 1953734.362, 953516.526 1...  11110
..        ...    ...                                                ...    ...
462  11740106    둔촌동  POLYGON ((969669.593 1948748.489, 969656.716 1...  11740
463  11740107    암사동  POLYGON ((968514.203 1950677.234, 968505.336 1...  11740
464  11740108    성내동  POLYGON ((967686.073 1948534.011, 967685.029 1...  11740
465  11740109    천호동  POLYGON ((968336.280 1950222.697, 968337.437 1...  11740
466  11740110    강일동  POLYGON ((970882.440 1951500.730, 970882.447 1...  11740

[467 rows x 4 columns]

In [39]:
# 시군구 코드와 서울시 구 이름 매핑
sigungu_mapping = {
    '11110': '종로구',
    '11140': '중구',
    '11170': '용산구',
    '11200': '성동구',
    '11215': '광진구',
    '11230': '동대문구',
    '11260': '중랑구',
    '11290': '성북구',
    '11305': '강북구',
    '11320': '도봉구',
    '11350': '노원구',
    '11380': '은평구',
    '11410': '서대문구',
    '11440': '마포구',
    '11470': '양천구',
    '11500': '강서구',
    '11530': '구로구',
    '11545': '금천구',
    '11560': '영등포구',
    '11590': '동작구',
    '11620': '관악구',
    '11650': '서초구',
    '11680': '강남구',
    '11710': '송파구',
    '11740': '강동구'
}

# gdf에 '구 이름' 열 추가하고 매핑된 이름으로 업데이트
gdf['구_이름'] = gdf['시군구_코드'].map(sigungu_mapping)

In [40]:
gdf

,읍면동_코드,읍면동_이름,geometry,시군구_코드,구_이름
0,11110101,청운동,"POLYGON ((953700.022 1954605.065, 953693.871 1...",11110,종로구
1,11110102,신교동,"POLYGON ((953233.465 1953996.984, 953235.183 1...",11110,종로구
2,11110103,궁정동,"POLYGON ((953560.228 1954257.466, 953561.190 1...",11110,종로구
3,11110104,효자동,"POLYGON ((953519.843 1953890.785, 953518.489 1...",11110,종로구
4,11110105,창성동,"POLYGON ((953516.123 1953734.362, 953516.526 1...",11110,종로구
...,...,...,...,...,...
462,11740106,둔촌동,"POLYGON ((969669.593 1948748.489, 969656.716 1...",11740,강동구
463,11740107,암사동,"POLYGON ((968514.203 1950677.234, 968505.336 1...",11740,강동구
464,11740108,성내동,"POLYGON ((967686.073 1948534.011, 967685.029 1...",11740,강동구
465,11740109,천호동,"POLYGON ((968336.280 1950222.697, 968337.437 1...",11740,강동구
466,11740110,강일동,"POLYGON ((970882.440 1951500.730, 970882.447 1...",11740,강동구

In [42]:
gdf = gdf.rename(columns={'읍면동_이름':'동', '구_이름':'구'})
gdf

,읍면동_코드,동,geometry,시군구_코드,구
0,11110101,청운동,"POLYGON ((953700.022 1954605.065, 953693.871 1...",11110,종로구
1,11110102,신교동,"POLYGON ((953233.465 1953996.984, 953235.183 1...",11110,종로구
2,11110103,궁정동,"POLYGON ((953560.228 1954257.466, 953561.190 1...",11110,종로구
3,11110104,효자동,"POLYGON ((953519.843 1953890.785, 953518.489 1...",11110,종로구
4,11110105,창성동,"POLYGON ((953516.123 1953734.362, 953516.526 1...",11110,종로구
...,...,...,...,...,...
462,11740106,둔촌동,"POLYGON ((969669.593 1948748.489, 969656.716 1...",11740,강동구
463,11740107,암사동,"POLYGON ((968514.203 1950677.234, 968505.336 1...",11740,강동구
464,11740108,성내동,"POLYGON ((967686.073 1948534.011, 967685.029 1...",11740,강동구
465,11740109,천호동,"POLYGON ((968336.280 1950222.697, 968337.437 1...",11740,강동구
466,11740110,강일동,"POLYGON ((970882.440 1951500.730, 970882.447 1...",11740,강동구

In [43]:
gdf = gdf.drop(columns=['읍면동_코드', '시군구_코드'])
gdf

       동                                           geometry    구
0    청운동  POLYGON ((953700.022 1954605.065, 953693.871 1...  종로구
1    신교동  POLYGON ((953233.465 1953996.984, 953235.183 1...  종로구
2    궁정동  POLYGON ((953560.228 1954257.466, 953561.190 1...  종로구
3    효자동  POLYGON ((953519.843 1953890.785, 953518.489 1...  종로구
4    창성동  POLYGON ((953516.123 1953734.362, 953516.526 1...  종로구
..   ...                                                ...  ...
462  둔촌동  POLYGON ((969669.593 1948748.489, 969656.716 1...  강동구
463  암사동  POLYGON ((968514.203 1950677.234, 968505.336 1...  강동구
464  성내동  POLYGON ((967686.073 1948534.011, 967685.029 1...  강동구
465  천호동  POLYGON ((968336.280 1950222.697, 968337.437 1...  강동구
466  강일동  POLYGON ((970882.440 1951500.730, 970882.447 1...  강동구

[467 rows x 3 columns]

In [45]:
gdf = gdf[['구', '동', 'geometry']]
gdf

       구    동                                           geometry
0    종로구  청운동  POLYGON ((953700.022 1954605.065, 953693.871 1...
1    종로구  신교동  POLYGON ((953233.465 1953996.984, 953235.183 1...
2    종로구  궁정동  POLYGON ((953560.228 1954257.466, 953561.190 1...
3    종로구  효자동  POLYGON ((953519.843 1953890.785, 953518.489 1...
4    종로구  창성동  POLYGON ((953516.123 1953734.362, 953516.526 1...
..   ...  ...                                                ...
462  강동구  둔촌동  POLYGON ((969669.593 1948748.489, 969656.716 1...
463  강동구  암사동  POLYGON ((968514.203 1950677.234, 968505.336 1...
464  강동구  성내동  POLYGON ((967686.073 1948534.011, 967685.029 1...
465  강동구  천호동  POLYGON ((968336.280 1950222.697, 968337.437 1...
466  강동구  강일동  POLYGON ((970882.440 1951500.730, 970882.447 1...

[467 rows x 3 columns]

In [47]:
gdf = gdf.to_crs(epsg=4326)
gdf

       구    동                                           geometry
0    종로구  청운동  POLYGON ((126.97556 37.58968, 126.97549 37.589...
1    종로구  신교동  POLYGON ((126.97031 37.58418, 126.97033 37.584...
2    종로구  궁정동  POLYGON ((126.97400 37.58654, 126.97401 37.586...
3    종로구  효자동  POLYGON ((126.97356 37.58323, 126.97355 37.582...
4    종로구  창성동  POLYGON ((126.97353 37.58182, 126.97354 37.581...
..   ...  ...                                                ...
462  강동구  둔촌동  POLYGON ((127.15669 37.53756, 127.15654 37.537...
463  강동구  암사동  POLYGON ((127.14353 37.55490, 127.14343 37.554...
464  강동구  성내동  POLYGON ((127.13424 37.53556, 127.13423 37.535...
465  강동구  천호동  POLYGON ((127.14153 37.55080, 127.14154 37.550...
466  강동구  강일동  POLYGON ((127.17030 37.56240, 127.17030 37.562...

[467 rows x 3 columns]

In [48]:
gdf.to_file("data/동경계_geo.shp", encoding='utf-8')